/* RightAware Laws & Legal Documents catalog (v3).
   SOURCE INTEGRITY RULES:
   - Entries with status:"uploaded" are REAL files supplied by the project owner and
     stored in assets/legal/. They open in the in-browser viewer and download as-is.
   - The original wording of a law is only ever shown from the supplied PDF (via
     content/law-text/*.js page extracts or the PDF viewer itself). Nothing is quoted
     from memory. extracted text = verbatim text layer of the supplied file.
   - docType separates legislation/gazettes from academic papers and compilations.
     A paper is never presented as legislation.
   - verification.status "source-file-supplied" means: the file exists and is the
     source we serve; its contents have NOT been cross-checked against an official
     published copy, and amendment/in-force status is NOT confirmed unless the PDF
     itself says so (see verification.note).
   - Entries with status:"awaiting-upload" remain catalog placeholders (no text).
   Schema: id, title, category, docType, jurisdiction, description, sourceNote,
   yearNote, status, file, textFile, pages, textAvailable, keywords,
   relatedRights [ids], verification {status, note}. */
window.RA_LAWS = [
  /* ---------- Real documents supplied by the project owner ---------- */
  { id:"constitution-1999", title:"Constitution of the Federal Republic of Nigeria 1999",
    category:"Constitution", docType:"legislation", jurisdiction:"Federal",
    description:"Nigeria's supreme law. This copy's text layer opens with the arrangement of sections and Chapter IV fundamental-rights provisions. Always confirm any amendment status against the official gazetted text.",
    sourceNote:"PDF supplied by the project owner (title page: “Constitution of the Federal Republic of Nigeria 1999”).",
    yearNote:"1999 (amendment status of this copy not confirmed — verify).",
    status:"uploaded", file:"assets/legal/constitution-of-nigeria-1999.pdf",
    textFile:"content/law-text/constitution-of-nigeria-1999.js", pages:137, textAvailable:true,
    keywords:"constitution fundamental rights chapter IV amendment supremacy citizen state",
    relatedRights:["fundamental","constitutional","fair-hearing","life","dignity","expression","movement","religion","privacy","association","property","civic"],
    verification:{ status:"source-file-supplied", note:"Text extracted from the supplied PDF. Not cross-checked against an official gazette copy; amendment status unconfirmed." } },

  { id:"electoral-act-2022", title:"Electoral Act 2022",
    category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Official-gazette copy of the Electoral Act 2022, covering elections, voting, party primaries, campaign and electoral offences (read the supplied text for the exact provisions).",
    sourceNote:"PDF supplied by the project owner; its first pages show “Federal Republic of Nigeria Official Gazette No. 61, Lagos – 29th March 2022, Vol. 109” and “Act No. 13 — Electoral Act, 2022”.",
    yearNote:"2022 (as printed in the supplied gazette).",
    status:"uploaded", file:"assets/legal/electoral-act-2022.pdf",
    textFile:"content/law-text/electoral-act-2022.js", pages:114, textAvailable:true,
    keywords:"electoral act election voting voter pvc primaries candidates campaign ballot results",
    relatedRights:["civic","constitutional","expression"],
    verification:{ status:"source-file-supplied", note:"Gazette headers visible in the supplied PDF. Not independently verified against INEC/National Assembly publications." } },

  { id:"laws-governing-elections", title:"Laws Governing Elections in Nigeria (compilation)",
    category:"Compilations", docType:"compilation", jurisdiction:"Federal",
    description:"Compilation supplied as one PDF: “Electoral Act 2010 (Updated)”, “INEC Regulations and Guidelines for the Conduct of Elections 2019” and “Extracts of 1999 Constitution of Nigeria”. Treat as a study compilation — it contains the 2010 Act material, while a separate Electoral Act 2022 PDF is also in this library.",
    sourceNote:"PDF supplied by the project owner (cover page as quoted above).",
    yearNote:"Contains 2010 Act material (updated) and 2019 INEC guidelines; check separately for current law.",
    status:"uploaded", file:"assets/legal/laws-governing-elections-in-nigeria.pdf",
    textFile:"content/law-text/laws-governing-elections-in-nigeria.js", pages:191, textAvailable:true,
    keywords:"elections inec regulations guidelines electoral act 2010 constitution extracts compilation",
    relatedRights:["civic","constitutional"],
    verification:{ status:"source-file-supplied", note:"Compilation, not a single instrument. 5 of 191 pages have no text layer. Which instruments are currently in force is not established by this file." } },

  { id:"acja-2015", title:"Administration of Criminal Justice Act 2015",
    category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Supplied as a 242-page scanned copy (image pages, no machine-readable text). Open it in the viewer or download it to read; full-text search is unavailable for this file until an official text version is supplied.",
    sourceNote:"Scanned PDF supplied by the project owner (file name: Administration-of-Criminal-Justice-Act-2015-2.pdf).",
    yearNote:"2015 (per file name; verify from the document itself).",
    status:"uploaded", file:"assets/legal/acja-2015.pdf",
    textFile:null, pages:242, textAvailable:false,
    keywords:"acja criminal justice arrest bail detention charge police procedure trial",
    relatedRights:["police","fair-hearing","fundamental"],
    verification:{ status:"source-file-supplied", note:"Scanned images — text not extractable, so contents cannot be verified or searched automatically. Read the original in the viewer." } },

  { id:"tenancy-law-2011", title:"Tenancy Law 2011 (Lagos State)",
    category:"State Laws", docType:"legislation", jurisdiction:"Lagos State",
    description:"Lagos State gazette law “to Regulate Rights and Obligations under Tenancy Agreements and the Relationship between the Landlord and the Tenant including the Procedure for recovery of premises”. Applies to Lagos State — tenancy law differs between states.",
    sourceNote:"PDF supplied by the project owner; first page shows “Lagos State of Nigeria Official Gazette No. 37, Vol. 44, 26 August 2011, Law No. 14”.",
    yearNote:"2011 (as printed in the supplied gazette).",
    status:"uploaded", file:"assets/legal/tenancy-law-2011.pdf",
    textFile:"content/law-text/tenancy-law-2011.js", pages:13, textAvailable:true,
    keywords:"tenancy rent landlord tenant lagos lease eviction recovery of premises notice",
    relatedRights:["tenancy","property"],
    verification:{ status:"source-file-supplied", note:"Gazette headers visible in the supplied PDF. Lagos State only; not cross-checked against an official Lagos publication." } },

  { id:"essential-principles-tenancy", title:"Understanding the Essential Principles of Landlord and Tenant Laws in Nigeria Through Judicial Decisions",
    category:"Academic Papers (not legislation)", docType:"academic-paper", jurisdiction:"—",
    description:"Academic paper by Bolaji S. Ramos (University of Lagos / Environmental Law Research Institute) on landlord-tenant principles through court decisions. Commentary — it is NOT the text of any law.",
    sourceNote:"PDF supplied by the project owner (author and affiliation from the paper's first page).",
    yearNote:"Year not stated on the extracted first page — check the document.",
    status:"uploaded", file:"assets/legal/essential-principles-tenancy-laws-nigeria.pdf",
    textFile:"content/law-text/essential-principles-tenancy-laws-nigeria.js", pages:25, textAvailable:true,
    keywords:"landlord tenant tenancy judicial decisions rent eviction commentary paper",
    relatedRights:["tenancy","property"],
    verification:{ status:"source-file-supplied", note:"Academic commentary, not legislation. Cases cited within are the author's — verify before relying on them." } },

  { id:"marriage-act", title:"Marriage Act",
    category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Marriage Act — arrangement of sections covers marriage districts, registrars, licences, notices, solemnisation and related offences (read the supplied text for exact provisions).",
    sourceNote:"PDF supplied by the project owner (first page: “MARRIAGE ACT — ARRANGEMENT OF SECTIONS”).",
    yearNote:"Year not shown on the extracted first page — check the supplied document for its edition.",
    status:"uploaded", file:"assets/legal/marriage-act.pdf",
    textFile:"content/law-text/marriage-act.js", pages:41, textAvailable:true,
    keywords:"marriage registrar notice wedding licence solemnisation districts spouses",
    relatedRights:["family"],
    verification:{ status:"source-file-supplied", note:"3 of 41 pages have no text layer. Edition/current status not confirmed — verify against an official copy." } },

  { id:"cybercrime-digital-transactions", title:"Cybercrime and Digital Transactions Law in Nigeria: A Review",
    category:"Academic Papers (not legislation)", docType:"academic-paper", jurisdiction:"—",
    description:"Academic review article by Ngozi Chisom Uzoka and Nneka Obiamaka Umejiaku (Department of Private & Property Law, Nnamdi Azikiwe University, Awka). Commentary on the law — NOT the text of any Act or bill.",
    sourceNote:"PDF supplied by the project owner (title, authors and affiliation from the paper's first page).",
    yearNote:"Year not stated on the extracted first page — check the document.",
    status:"uploaded", file:"assets/legal/cybercrime-digital-transactions-law-nigeria.pdf",
    textFile:"content/law-text/cybercrime-digital-transactions-law-nigeria.js", pages:7, textAvailable:true,
    keywords:"cybercrime digital transactions online fraud review paper commentary efcc cybercrime act",
    relatedRights:["digital","consumer"],
    verification:{ status:"source-file-supplied", note:"Academic article, not legislation. A duplicate copy of the same file also exists in Downloads (not stored twice)." } },

  { id:"national-policy-education", title:"National Policy on Education",
    category:"Government Publications", docType:"government-publication", jurisdiction:"Federal",
    description:"National Policy on Education — a federal policy publication (supplied as an 87-page scanned copy with no machine-readable text). Policy document, not an Act; open the viewer or download to read.",
    sourceNote:"Scanned PDF supplied by the project owner (file name: NATIONAL-POLICY-ON-EDUCATION.pdf).",
    yearNote:"Edition/year not machine-readable — check the document itself.",
    status:"uploaded", file:"assets/legal/national-policy-on-education.pdf",
    textFile:null, pages:87, textAvailable:false,
    keywords:"education policy schools curriculum national policy children students",
    relatedRights:["education","children"],
    verification:{ status:"source-file-supplied", note:"Scanned images — no text extraction possible; contents not verified. Policy publication, not legislation." } },

  { id:"citizenship-responsibility", title:"Citizenship and Responsibility in Nigeria: A Legal Appraisal",
    category:"Academic Papers (not legislation)", docType:"academic-paper", jurisdiction:"—",
    description:"Academic appraisal of citizenship and civic responsibility in Nigeria. Commentary — NOT legislation. Useful background for the Civic Responsibilities topic.",
    sourceNote:"PDF supplied by the project owner (title from the document's first page).",
    yearNote:"Year not stated on the extracted first page — check the document.",
    status:"uploaded", file:"assets/legal/citizenship-responsibility-nigeria-legal-appraisal.pdf",
    textFile:"content/law-text/citizenship-responsibility-nigeria-legal-appraisal.js", pages:3, textAvailable:true,
    keywords:"citizenship responsibility civic duties legal appraisal paper nigeria",
    relatedRights:["civic","constitutional"],
    verification:{ status:"source-file-supplied", note:"Academic commentary, not legislation." } },

  { id:"international-law-dualism", title:"The Application of International Law in Nigeria and the Façade of Dualism",
    category:"Academic Papers (not legislation)", docType:"academic-paper", jurisdiction:"—",
    description:"Academic paper (author name shown on the document: Elijah Oluwatoyin Okebukola) discussing how international law operates in Nigeria and the Constitution's treaty provisions. Commentary — NOT legislation.",
    sourceNote:"PDF supplied by the project owner (title and author from the document's first page).",
    yearNote:"Year not stated on the extracted first page — check the document.",
    status:"uploaded", file:"assets/legal/application-international-law-nigeria-dualism.pdf",
    textFile:"content/law-text/application-international-law-nigeria-dualism.js", pages:14, textAvailable:true,
    keywords:"international law dualism treaties section 12 constitution nigeria paper",
    relatedRights:["constitutional","fundamental"],
    verification:{ status:"source-file-supplied", note:"Academic commentary, not legislation." } },

  /* ---------- Catalog placeholders (awaiting verified upload) ---------- */
  { id:"police-act-2020", title:"Police Act 2020", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Framework for police powers, duties and conduct. Catalog placeholder — document to be uploaded after verification.",
    sourceHint:"Official gazette (verify).", yearNote:"2020 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"police act powers duties conduct",
    relatedRights:["police","fundamental","dignity"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"land-use-act-1978", title:"Land Use Act 1978", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Land tenure and use framework. Catalog placeholder — document to be uploaded after verification.",
    sourceHint:"Official gazette (verify).", yearNote:"1978 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"land use act tenure governor allocation",
    relatedRights:["property","tenancy"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"child-rights-act-2003", title:"Child Rights Act 2003", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Rights and protection of children (federal; domesticated unevenly by states). Catalog placeholder.",
    sourceHint:"Official gazette; confirm state domestication (verify).", yearNote:"2003 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"child rights children protection welfare",
    relatedRights:["children","women","education"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"vapp-act-2015", title:"Violence Against Persons (Prohibition) Act 2015", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Protection against gender-based and other violence (federal; domesticated unevenly). Catalog placeholder.",
    sourceHint:"Official gazette; confirm state domestication (verify).", yearNote:"2015 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"vapp violence persons protection gender",
    relatedRights:["women","children","dignity"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"fccpa-2018", title:"Federal Competition and Consumer Protection Act 2018", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Consumer protection and competition framework. Catalog placeholder.",
    sourceHint:"Official gazette (verify).", yearNote:"2018 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"consumer protection competition fccpc",
    relatedRights:["consumer","digital"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"disabilities-act-2018", title:"Discrimination Against Persons with Disabilities (Prohibition) Act 2018", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Protection and inclusion of persons with disabilities. Catalog placeholder.",
    sourceHint:"Official gazette (verify).", yearNote:"2018 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"disability discrimination inclusion access",
    relatedRights:["disability","employment","education"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"ndpa-2023", title:"Nigeria Data Protection Act 2023", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Personal data handling rules. Catalog placeholder — verify current text and regulator guidance.",
    sourceHint:"Official gazette / regulator (verify).", yearNote:"2023 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"data protection privacy ndpa personal data",
    relatedRights:["digital","privacy"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"anti-torture-2017", title:"Anti-Torture Act 2017", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Prohibition of torture and cruel, inhuman or degrading treatment. Catalog placeholder.",
    sourceHint:"Official gazette (verify).", yearNote:"2017 (verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"torture cruel inhuman degrading treatment confession",
    relatedRights:["dignity","police","fundamental"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"labour-act", title:"Labour Act (as amended)", category:"Acts", docType:"legislation", jurisdiction:"Federal",
    description:"Employment, wages and conditions of service framework. Catalog placeholder — upload a verified copy to enable search.",
    sourceHint:"Official gazette (verify current version).", yearNote:"Core Act long-standing; amendments to verify.",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"labour employment wages salary conditions service termination",
    relatedRights:["employment"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"fccpc-consumer-regulations", title:"Consumer protection regulations & guidance", category:"Regulations", docType:"regulations", jurisdiction:"Federal",
    description:"Placeholder for consumer-protection regulations/guidance once an official copy is supplied.",
    sourceHint:"Regulator publications (verify).", yearNote:"(verify).",
    status:"awaiting-upload", file:null, textFile:null, pages:null, textAvailable:false,
    keywords:"consumer regulations guidance refund goods services",
    relatedRights:["consumer"],
    verification:{ status:"awaiting-verification", source:"", date:"" } }
];

window.RA_LAW_CATEGORIES = [
  "Constitution","Acts","State Laws","Regulations","Compilations",
  "Legal Documents","Government Publications","Academic Papers (not legislation)",
  "Court Resources","Simplified Explanations"
];

/* Topic → supplied documents & search terms.
   These are SEARCH ENTRY POINTS into the supplied PDFs (not curated legal citations).
   They point a visitor at the documents most likely to contain a topic's wording;
   the snippets returned are the documents' own extracted text with page numbers.
   Scanned documents (textAvailable:false) still link — they open in the viewer. */
window.RA_TOPIC_LAWS = {
  "fundamental":      [{ doc:"constitution-1999", q:"fundamental rights" }],
  "police":           [{ doc:"constitution-1999", q:"arrest" }, { doc:"acja-2015", q:"arrest" }],
  "fair-hearing":     [{ doc:"constitution-1999", q:"fair hearing" }, { doc:"acja-2015", q:"trial" }],
  "life":             [{ doc:"constitution-1999", q:"right to life" }],
  "dignity":          [{ doc:"constitution-1999", q:"dignity of his person" }],
  "expression":       [{ doc:"constitution-1999", q:"freedom of expression" }],
  "movement":         [{ doc:"constitution-1999", q:"freedom of movement" }],
  "religion":         [{ doc:"constitution-1999", q:"freedom of religion" }],
  "privacy":          [{ doc:"constitution-1999", q:"private and family life" }],
  "association":      [{ doc:"constitution-1999", q:"assembly and association" }],
  "property":         [{ doc:"constitution-1999", q:"property" }, { doc:"tenancy-law-2011", q:"premises" }],
  "employment":       [{ doc:"constitution-1999", q:"employment" }],
  "tenancy":          [{ doc:"tenancy-law-2011", q:"tenant" }, { doc:"essential-principles-tenancy", q:"landlord" }],
  "consumer":         [{ doc:"cybercrime-digital-transactions", q:"consumer" }],
  "women":            [{ doc:"constitution-1999", q:"women" }],
  "children":         [{ doc:"constitution-1999", q:"child" }, { doc:"national-policy-education", q:"education" }],
  "disability":       [{ doc:"constitution-1999", q:"disability" }],
  "education":        [{ doc:"national-policy-education", q:"education" }, { doc:"citizenship-responsibility", q:"education" }],
  "digital":          [{ doc:"cybercrime-digital-transactions", q:"cybercrime" }, { doc:"constitution-1999", q:"private and family life" }],
  "constitutional":   [{ doc:"constitution-1999", q:"legislative powers" }],
  "civic":            [{ doc:"electoral-act-2022", q:"voter" }, { doc:"laws-governing-elections", q:"election" }, { doc:"citizenship-responsibility", q:"responsibility" }],
  "environment":      [{ doc:"constitution-1999", q:"environment" }]
};
