/* RightAware Laws & Legal Documents catalog (v2).
   HONESTY RULE: only well-known instrument TITLES are listed as catalog placeholders.
   No document text, section quotes, or download files are included until verified
   uploads are provided. status: "awaiting-upload" for all v2 entries.
   Schema per entry: id, title, category, description, sourceHint, yearNote, status,
   fileRef (null until uploaded), relatedRights [ids], verification {status, source, date}. */
window.RA_LAWS = [
  { id:"constitution-1999", title:"Constitution of the Federal Republic of Nigeria 1999 (as amended)", category:"Constitution",
    description:"Nigeria's supreme law. Catalog placeholder — official text to be uploaded after verification of the amended version.",
    sourceHint:"Official gazette / National Assembly (verify).", yearNote:"1999, with amendments (verify latest).",
    status:"awaiting-upload", fileRef:null, relatedRights:["fundamental","constitutional","fair-hearing","life","dignity","expression","movement","religion","privacy","association","property"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"police-act-2020", title:"Police Act 2020", category:"Acts",
    description:"Framework for police powers, duties and conduct. Catalog placeholder — document to be uploaded after verification.",
    sourceHint:"Official gazette (verify).", yearNote:"2020 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["police","fundamental","dignity"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"acja-2015", title:"Administration of Criminal Justice Act 2015", category:"Acts",
    description:"Criminal procedure for federal courts and the FCT. Catalog placeholder — document to be uploaded after verification.",
    sourceHint:"Official gazette (verify).", yearNote:"2015 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["police","fair-hearing","fundamental"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"electoral-act-2022", title:"Electoral Act 2022", category:"Acts",
    description:"Elections, voter registration and offences. Catalog placeholder — document to be uploaded after verification.",
    sourceHint:"Official gazette / INEC guidance (verify).", yearNote:"2022 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["civic","constitutional","expression"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"land-use-act-1978", title:"Land Use Act 1978", category:"Acts",
    description:"Land tenure and use framework. Catalog placeholder — document to be uploaded after verification.",
    sourceHint:"Official gazette (verify).", yearNote:"1978 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["property","tenancy"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"child-rights-act-2003", title:"Child Rights Act 2003", category:"Acts",
    description:"Rights and protection of children (federal; domesticated unevenly by states). Catalog placeholder.",
    sourceHint:"Official gazette; confirm state domestication (verify).", yearNote:"2003 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["children","women","education"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"vapp-act-2015", title:"Violence Against Persons (Prohibition) Act 2015", category:"Acts",
    description:"Protection against gender-based and other violence (federal; domesticated unevenly). Catalog placeholder.",
    sourceHint:"Official gazette; confirm state domestication (verify).", yearNote:"2015 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["women","children","dignity"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"fccpa-2018", title:"Federal Competition and Consumer Protection Act 2018", category:"Acts",
    description:"Consumer protection and competition framework. Catalog placeholder.",
    sourceHint:"Official gazette (verify).", yearNote:"2018 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["consumer","digital"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"disabilities-act-2018", title:"Discrimination Against Persons with Disabilities (Prohibition) Act 2018", category:"Acts",
    description:"Protection and inclusion of persons with disabilities. Catalog placeholder.",
    sourceHint:"Official gazette (verify).", yearNote:"2018 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["disability","employment","education"],
    verification:{ status:"awaiting-verification", source:"", date:"" } },
  { id:"ndpa-2023", title:"Nigeria Data Protection Act 2023", category:"Acts",
    description:"Personal data handling rules. Catalog placeholder — verify current text and regulator guidance.",
    sourceHint:"Official gazette / regulator (verify).", yearNote:"2023 (verify).",
    status:"awaiting-upload", fileRef:null, relatedRights:["digital","privacy"],
    verification:{ status:"awaiting-verification", source:"", date:"" } }
];
window.RA_LAW_CATEGORIES = ["Constitution","Acts","Regulations","Legal Documents","Government Publications","Court Resources","Simplified Explanations"];
