/* RightAware detailed rights content (v3) — SINGLE SOURCE OF TRUTH for the Rights Library.
   Rendered by rights/topic.html. Editable: add/edit entries following this schema.
   status: "full-guide" (complete, reviewed) | "partial" (good draft, needs legal review)
           | "overview" (general information, full guide awaiting research + verification).
   Rule: never invent section numbers, cases, contacts or statistics. Anything not yet
   verified uses status "overview" and a VERIFY source hint. Works from file:// (plain JS).

   TO ADD A RIGHTS CATEGORY: add ONE entry below (id must be unique and lowercase).
   It automatically appears in the Rights Library grid, the homepage counts, the
   Resources guides list and site search — no other file needs editing.
   data.js derives window.RA_RIGHTS from this list; do not define RA_RIGHTS elsewhere. */
window.RA_RIGHTS_DETAIL = [
{ id:"fundamental", icon:"🛡", title:"Fundamental Human Rights", status:"partial",
  summary:"The basic rights every person in Nigeria is entitled to — life, dignity, liberty, fair hearing, privacy, expression, movement and more.",
  explanation:["Fundamental rights are the minimum guarantees every person holds simply by being human. In Nigeria they are set out in Chapter IV of the 1999 Constitution (as amended).","These rights limit what the government — and in some cases private actors — can lawfully do to you, and they can be enforced through the courts."],
  legalBasis:{ text:"1999 Constitution of Nigeria, Chapter IV (as amended). Enforcement procedure: Fundamental Rights Enforcement Procedure Rules (verify current version).", status:"verify" },
  meaning:["You are entitled to these rights regardless of income, gender, ethnicity, religion or disability.","Some rights are absolute (e.g. freedom from torture); others may be limited by laws that are reasonably justifiable (verify each case).","If a fundamental right is violated, you can seek redress in court — get a lawyer early."],
  canDo:["Learn the rights in Chapter IV in plain language (start with each topic in this library).","Document violations: dates, places, people involved, photos, medical reports, witnesses.","Report through proper channels (see Get Help) and seek legal advice promptly — time limits can apply."],
  avoid:["Do not assume every unfair situation is a constitutional violation — some disputes are civil or administrative.","Do not delay: evidence fades and some actions have deadlines.","Do not confront armed or hostile actors physically; protect your safety first."],
  examples:[{t:"Workplace query vs rights violation",d:"Being queried at work is generally an employment matter; being detained or beaten by police over the same dispute may raise fundamental-rights issues."},{t:"Eviction",d:"A landlord locking you out raises tenancy-law issues and may also touch on your right to dignity and property — document everything."}],
  faqs:[{q:"Where are my fundamental rights written?",a:"Chapter IV of the 1999 Constitution (as amended). Always confirm against the official gazetted text."},{q:"Can I go to court myself?",a:"You can, but fundamental-rights cases have technical rules. A lawyer or legal-aid clinic greatly improves your chances."}],
  related:["police","fair-hearing","life","dignity","expression"], orgs:["Human-rights protection body","Legal Aid (free legal assistance)"], sources:["VERIFY: official text of the 1999 Constitution (as amended), Chapter IV."],
  keywords:"fundamental human rights constitution chapter iv enforce court" },
{ id:"police", icon:"🚔", title:"Police & Arrest Rights", status:"full-guide", fullGuide:"rights/arrest-rights.html",
  summary:"What police can and cannot do, your right to silence and a lawyer, bail rules, detention time limits, and how to report abuse.",
  explanation:["This topic has a complete step-by-step guide. You are being redirected to it."],
  legalBasis:{ text:"1999 Constitution S.35–36; Police Act 2020; ACJA 2015; Anti-Torture Act 2017 (verify citations).", status:"verified" },
  meaning:["See the full guide."], canDo:["Open the full guide."], avoid:["Do not pay for bail."],
  examples:[], faqs:[], related:["fundamental","fair-hearing","life","dignity"], orgs:["Police complaints unit","Human-rights protection body"],
  sources:["rights/arrest-rights.html"], keywords:"police arrest bail detain station silence lawyer charge search" },
{ id:"fair-hearing", icon:"⚖", title:"Right to Fair Hearing", status:"overview",
  summary:"Anyone accused of an offence is presumed innocent and entitled to a fair, public hearing within a reasonable time.",
  explanation:["Fair hearing means your case must be decided by an impartial authority, with a chance to present your side, challenge evidence, and be represented.","It covers criminal trials and, in adapted form, many administrative decisions affecting your rights (verify scope with a lawyer)."],
  legalBasis:{ text:"General information: fair-hearing guarantees are associated with the 1999 Constitution (verify exact section) and the ACJA 2015 for criminal trials (verify).", status:"verify" },
  meaning:["You are presumed innocent until proven guilty.","You should have adequate time and facilities to prepare a defence.","Proceedings should be free from bias, delay, or intimidation."],
  canDo:["Ask for the charge against you in writing and keep copies of all court processes.","Attend every hearing; note dates, orders and what was said.","Get a lawyer; if you cannot afford one, ask about free legal-aid options."],
  avoid:["Do not ignore court summons or hearing dates — absence can lead to adverse orders.","Do not discuss an ongoing case publicly in ways that could prejudice it.","Do not sign statements or agreements you do not understand."],
  examples:[{t:"Adjournments",d:"Repeated unexplained adjournments delaying your trial can be raised through your lawyer as a fair-hearing concern."},{t:"Workplace panel",d:"A disciplinary panel that refuses to let you respond or bring a representative may be procedurally unfair — document it."}],
  faqs:[{q:"Does fair hearing apply to non-court panels?",a:"Fairness principles apply widely, but the exact legal position depends on the body and the law setting it up — get advice."},{q:"What if my trial is delayed for years?",a:"Discuss with your lawyer; prolonged delay can be challenged — keep records of all adjournments."}],
  related:["fundamental","police","life"], orgs:["Legal Aid (free legal assistance)","Human-rights protection body"], sources:["VERIFY: Constitution fair-hearing provision; ACJA 2015; court rules of the relevant court."],
  keywords:"fair hearing trial innocent defence court delay adjournment" },
{ id:"life", icon:"❤️", title:"Right to Life", status:"overview",
  summary:"Every person has the right to life. No one should be arbitrarily deprived of it.",
  explanation:["The right to life is the foundation of all other rights. It prohibits arbitrary killing, including unlawful use of lethal force.","Threats to life — including excessive force by security agents — are among the most serious violations and should be documented and reported."],
  legalBasis:{ text:"General information: right-to-life guarantees sit within the 1999 Constitution's fundamental rights chapter (verify exact section).", status:"verify" },
  meaning:["Life may only be taken within strictly lawful exceptions defined by law (verify).","The state has a duty to investigate suspicious deaths.","You have the right to self-preservation, including seeking protection when threatened."],
  canDo:["If threatened, prioritise safety: leave, alert trusted people, contact official emergency channels.","Document threats (messages, witnesses, times) and report promptly.","Families of victims should preserve evidence and seek legal counsel quickly."],
  avoid:["Do not take the law into your own hands — retaliation creates new liability.","Do not clean up or disturb a scene before authorities document it, where safe and lawful.","Do not delay reporting; early reports preserve evidence."],
  examples:[{t:"Threat messages",d:"Screenshot threats immediately, back them up, and report — do not just delete them."},{t:"Excessive force",d:"Any use of force by security agents causing death or grave injury should be independently reported and investigated."}],
  faqs:[{q:"What should I do first if someone threatens my life?",a:"Get somewhere safe, tell trusted people, preserve the evidence, and report to the appropriate authorities."},{q:"Can the families of victims get justice?",a:"Alleged unlawful killings can be reported, investigated and prosecuted — a lawyer should guide the family."}],
  related:["fundamental","police","dignity"], orgs:["Human-rights protection body","Legal Aid (free legal assistance)"], sources:["VERIFY: Constitution right-to-life provision; criminal laws on homicide (federal/state)."],
  keywords:"life killing murder threat force death unlawful" },
{ id:"dignity", icon:"🤝", title:"Dignity of the Human Person", status:"overview",
  summary:"No one should be subjected to torture, inhuman or degrading treatment, slavery or forced labour.",
  explanation:["Human dignity protects you against torture, beatings, humiliation rituals, and degrading punishment — whether by officials or private actors.","This right is especially relevant in detention, workplaces, schools, and domestic settings."],
  legalBasis:{ text:"General information: dignity and anti-torture guarantees (Constitution; Anti-Torture Act 2017 — verify exact provisions).", status:"verify" },
  meaning:["Torture to extract confessions is prohibited; coerced confessions are challengeable.","Degrading treatment (e.g. parading, severe humiliation) can be a violation even without physical injury.","Forced labour and slavery-like practices are prohibited."],
  canDo:["Seek medical care immediately after any assault and obtain a medical report from a recognised facility.","Photograph injuries (with consent of the victim) and preserve torn clothing or other evidence.","Report through Get Help channels and consult a lawyer about redress."],
  avoid:["Do not 'settle' serious assaults informally before documenting and getting advice — you may waive remedies.","Do not sign statements minimising what happened.","Do not stay silent out of shame; support services exist."],
  examples:[{t:"Beating in custody",d:"Injuries sustained in custody should be medically documented at once and reported outside the chain of command involved."},{t:"Workplace assault",d:"A supervisor who beats or grievously humiliates staff may face both criminal and civil consequences — document and report."}],
  faqs:[{q:"Is slapping someone a violation?",a:"Assault is unlawful; whether it amounts to a constitutional dignity violation depends on gravity and context — report assaults regardless."},{q:"What evidence matters most?",a:"Medical reports, photos, witnesses and prompt complaints carry the most weight."}],
  related:["fundamental","police","life","women","children"], orgs:["Human-rights protection body","Legal Aid (free legal assistance)","Domestic & sexual-violence support services"], sources:["VERIFY: Constitution dignity provision; Anti-Torture Act 2017."],
  keywords:"dignity torture inhuman degrading beating assault forced labour" },
{ id:"expression", icon:"🗣", title:"Freedom of Expression", status:"overview",
  summary:"You may hold opinions and express ideas — online and offline — within limits set by law such as defamation and public order.",
  explanation:["Freedom of expression covers speech, writing, art, journalism, protest messaging and online posts.","It is not unlimited: laws on defamation, incitement, and other lawful restrictions apply (verify scope). Peaceful, truthful expression is the safest ground."],
  legalBasis:{ text:"General information: expression guarantees sit within the Constitution's fundamental rights chapter (verify exact section); defamation and cybercrime rules set boundaries (verify current laws).", status:"verify" },
  meaning:["You can criticise policies and public officials on matters of public interest, sticking to facts.","Journalists, bloggers and activists have the same core protection, with professional/legal risks to manage.","Online posts carry the same liability as offline statements."],
  canDo:["Verify facts before publishing allegations; keep your evidence.","Use peaceful, lawful channels: petitions, press, town halls, courts, the ballot.","If arrested over expression, invoke your right to silence and call a lawyer."],
  avoid:["Do not publish unverified criminal allegations against named individuals.","Do not incite violence or ethnic/religious hatred — it is dangerous and unlawful.","Do not assume anonymity online protects you; act as if posts are public."],
  examples:[{t:"Criticising a policy",d:"A factual critique of a government policy citing public records is classic protected expression."},{t:"Viral accusation",d:"Sharing an unconfirmed rape or fraud allegation with a name and photo risks defamation liability — verify first."}],
  faqs:[{q:"Can I be arrested for a social media post?",a:"Posts can attract liability (e.g. defamation, cybercrime provisions). Stay factual and peaceful; get a lawyer if contacted by authorities."},{q:"Are protests legal?",a:"Peaceful assembly and expression are constitutionally grounded, but notifications, routes and policing rules apply — verify current requirements and stay peaceful."}],
  related:["fundamental","digital","association","religion"], orgs:["Human-rights protection body","Legal Aid (free legal assistance)"], sources:["VERIFY: Constitution expression provision; defamation law; cybercrime legislation (as amended)."],
  keywords:"expression speech press protest social media post defamation opinion" },
{ id:"movement", icon:"🧭", title:"Freedom of Movement", status:"overview",
  summary:"You may move freely within Nigeria, reside where you choose, and leave or enter the country subject to lawful immigration controls.",
  explanation:["Internal checkpoints, curfews, and travel restrictions must have lawful backing. Routine harassment at roadblocks is a common complaint.","Your right to reside in any part of Nigeria cannot be overridden by local custom alone (verify specific disputes)."],
  legalBasis:{ text:"General information: movement guarantees sit within the Constitution's fundamental rights chapter (verify exact section).", status:"verify" },
  meaning:["You can live, work and travel in any state.","Restrictions (e.g. curfews, emergency orders) must be lawful, time-bound and properly issued.","You cannot be banished or internally exiled without due process."],
  canDo:["Carry valid ID when travelling; stay calm and polite at checkpoints.","Note the location, time, unit and behaviour if harassed; report afterwards.","Check for officially announced curfews or restrictions before inter-state travel at tense periods."],
  avoid:["Do not attempt to force your way through a security cordon — comply, document, report.","Do not travel without any identification during heightened security operations.","Do not pay 'pass money' at checkpoints; note and report extortion."],
  examples:[{t:"Roadblock delay",d:"Being waved through after ID check is normal; being detained for hours or forced to pay is reportable."},{t:"Relocation",d:"No community can lawfully expel a lawful resident without due process — document threats and report."}],
  faqs:[{q:"Must I carry ID everywhere?",a:"There is no single 'carry ID always' offence, but valid ID smooths security encounters — keep some form of ID when travelling."},{q:"Can police stop my vehicle?",a:"Yes, for lawful checks and reasonable suspicion — but searches, detention and demands for money have limits (see Police & Arrest Rights)."}],
  related:["fundamental","police","dignity"], orgs:["Human-rights protection body","Police complaints unit"], sources:["VERIFY: Constitution movement provision."],
  keywords:"movement travel roadblock checkpoint curfew reside relocate id" },
{ id:"religion", icon:"🕊", title:"Freedom of Religion", status:"overview",
  summary:"You may practise, change, and share your religion — alone or in community — subject to public safety, order, health and others' rights.",
  explanation:["Nigeria's diversity makes religious freedom and tolerance central to civic life. No one may be compelled to adopt or renounce a faith.","Religious practice does not exempt anyone from generally applicable lawful duties (verify specific conflicts)."],
  legalBasis:{ text:"General information: religion guarantees sit within the Constitution's fundamental rights chapter (verify exact section).", status:"verify" },
  meaning:["Worship, dress, diet, holidays and propagation are protected dimensions.","Forced conversion, and discrimination in public services on religious grounds, are challengeable.","Inter-religious disputes should be resolved peacefully through lawful channels."],
  canDo:["Practise openly and peacefully; document any discrimination or attack.","Use mediation, community leaders and lawful complaints channels for disputes.","Teach tolerance: most conflicts de-escalate with early, calm intervention."],
  avoid:["Do not use religion to justify violence, threats or hate speech.","Do not take disputes to street confrontations — report and mediate.","Do not assume every scheduling conflict is discrimination; seek facts first."],
  examples:[{t:"Workplace holiday",d:"Denied leave for a major religious observance while others get theirs may be worth a written query and escalation."},{t:"School dress",d:"Dress-code disputes involving faith should go through the school's formal channels with parents/guardians involved."}],
  faqs:[{q:"Can a school ban religious dress?",a:"It depends on the school's status, rules and the specific facts — raise it formally and seek advice."},{q:"What if my community threatens me over my faith?",a:"Prioritise safety, preserve evidence, and report to appropriate authorities."}],
  related:["fundamental","expression","association","education"], orgs:["Human-rights protection body"], sources:["VERIFY: Constitution religion provision."],
  keywords:"religion faith worship church mosque hijab convert belief" },
{ id:"privacy", icon:"🔒", title:"Right to Privacy", status:"overview",
  summary:"Your home, correspondence, and personal data are protected. Searches, surveillance and data processing need lawful basis.",
  explanation:["Privacy covers your home, phone, letters, and personal information held by companies and government.","Phone searches, home invasions without process, and reckless sharing of personal data can all be violations."],
  legalBasis:{ text:"General information: privacy guarantees (Constitution) plus data-protection and cybercrime legislation (verify current laws, incl. Nigeria Data Protection Act 2023).", status:"verify" },
  meaning:["Your phone and home generally require consent or proper legal process before search.","Organisations handling your data owe you care, purpose limitation and security.","You can complain about misuse of your personal information."],
  canDo:["State calmly that you do not consent to phone/home searches without proper process — then comply physically if forced and report after.","Read app and service privacy terms before sharing sensitive data.","Complain in writing to the organisation first; escalate to the relevant regulator if unresolved."],
  avoid:["Do not physically resist a search — document and challenge it later.","Do not share others' personal data (photos, numbers, addresses) publicly.","Do not ignore data-breach notices affecting your accounts."],
  examples:[{t:"Phone check at roadblock",d:"You may decline consent; if officers force it, note details and report rather than fighting."},{t:"Loan app harassment",d:"Apps blasting your contacts over a loan may breach data-protection rules — screenshot, complain, escalate."}],
  faqs:[{q:"Can my employer read my personal emails?",a:"Generally no, without clear policy and lawful basis — raise it formally and seek advice."},{q:"What is the data-protection complaint path?",a:"Complain to the organisation, then to the data-protection authority — verify the current channel in official guidance."}],
  related:["fundamental","digital","police","expression"], orgs:["Human-rights protection body"], sources:["VERIFY: Constitution privacy provision; Nigeria Data Protection Act 2023 and regulator guidance."],
  keywords:"privacy phone search home data personal information surveillance" },
{ id:"association", icon:"👥", title:"Freedom of Association & Assembly", status:"overview",
  summary:"You may join groups, unions, and peaceful assemblies — and choose not to join.",
  explanation:["This covers political parties, unions, professional bodies, student groups and peaceful protests.","Peaceful assembly is protected; violence, weapons, and blockades of others' rights are not."],
  legalBasis:{ text:"General information: association/assembly guarantees sit within the Constitution's fundamental rights chapter (verify exact section); public-order rules may apply to processions (verify).", status:"verify" },
  meaning:["No one can force you to join or remain in an association.","Workers may organise for collective bargaining subject to labour law.","Peaceful protest messaging is protected expression; conduct must stay peaceful and lawful."],
  canDo:["Register associations properly (verify current corporate/regulatory procedure).","Keep protests peaceful, unarmed, and coordinated; designate marshals and document everything.","Join a union or professional body relevant to your protection."],
  avoid:["Do not carry weapons to any gathering — it destroys legal protection.","Do not block hospitals, roads or others' access as a tactic.","Do not assume social-media mobilisation exempts you from public-order rules."],
  examples:[{t:"Union dues dispute",d:"Deductions and representation questions go through the union's constitution and labour channels."},{t:"Campus fellowship",d:"Student groups denied registration need written reasons — appeal through the institution's formal process."}],
  faqs:[{q:"Do protests need police permission?",a:"Rules on notification vs permission are contested — verify current legal position, keep everything peaceful, and get advice for large actions."},{q:"Can I be sacked for joining a union?",a:"Victimisation for lawful union activity is challengeable — document everything and seek advice."}],
  related:["fundamental","expression","employment","religion"], orgs:["Human-rights protection body","Legal Aid (free legal assistance)"], sources:["VERIFY: Constitution association provision; labour and public-order laws."],
  keywords:"association assembly protest union party group join" },
{ id:"property", icon:"🏡", title:"Property Rights", status:"overview",
  summary:"You may own movable and immovable property. Compulsory acquisition requires public purpose and prompt compensation.",
  explanation:["Land, houses, shops, vehicles and goods are protected. Government can compulsorily acquire land only for public purposes and with compensation (verify procedure).","Land transactions are a major fraud area — verification before payment is essential."],
  legalBasis:{ text:"General information: property guarantees (Constitution) and the Land Use Act 1978 (verify provisions); state land-registration rules apply.", status:"verify" },
  meaning:["Ownership documents (receipts, deeds, registered titles, C of O processes) are your shield — keep them safe.","'Omo onile'/land-grabber demands have no legal standing — report them.","Tenants and landlords each hold distinct protected interests (see Rent & Tenancy)."],
  canDo:["Verify land at the relevant land registry and inspect physically before paying anything.","Use a lawyer for agreements; register documents where the law requires it.","Insure and document valuable property (photos, serials, receipts)."],
  avoid:["Do not buy land based only on an agent's word or social-media adverts.","Do not pay in cash without receipts and witnesses.","Do not demolish, lock out, or seize property to 'enforce' your own claim — use lawful process."],
  examples:[{t:"Two buyers, one plot",d:"Whoever perfects title properly usually prevails — this is why registry verification and a lawyer matter."},{t:"Road expansion notice",d:"Compulsory acquisition notices should state the public purpose and compensation process — get advice before signing anything."}],
  faqs:[{q:"Is a family receipt enough for land?",a:"It is evidence, but perfection/registration strengthens title greatly — verify at the registry with a lawyer."},{q:"Can government take my land?",a:"Only through lawful compulsory acquisition for public purpose with compensation — challenge defects through counsel."}],
  related:["fundamental","tenancy","constitutional"], orgs:["Legal Aid (free legal assistance)"], sources:["VERIFY: Constitution property provision; Land Use Act 1978; state registration laws."],
  keywords:"property land house plot c of o deed ownership acquire compensation grabber" },
{ id:"employment", icon:"💼", title:"Employment Rights", status:"overview",
  summary:"Hiring, pay, dismissal, workplace safety and what to do about unpaid salary or unfair sacking.",
  explanation:["Work relationships should rest on clear written terms. Disputes turn on documents: offer letters, payslips, queries, and termination letters.","Minimum wage, working hours, leave, safety, and protection against unfair dismissal are governed by labour law (verify current statutes)."],
  legalBasis:{ text:"General information: Labour Act, Minimum Wage Act (as amended — verify), National Industrial Court jurisdiction (verify).", status:"verify" },
  meaning:["You should receive agreed pay, on time, with records.","Dismissal should follow due process stated in your contract and staff rules.","You are entitled to a safe workplace and defined leave."],
  canDo:["Get terms in writing before resuming; keep every pay slip and official letter.","Raise grievances in writing and keep copies with dates.","For unpaid wages or abrupt dismissal, make a formal written demand, then escalate (see Get Help)."],
  avoid:["Do not resign in anger without advice — it can weaken claims.","Do not work without any written terms where avoidable.","Do not ignore queries or warnings; respond factually and keep copies."],
  examples:[{t:"Three months unpaid",d:"A dated demand letter listing months owed, with payslip/bank evidence, is step one before escalation."},{t:"Summary dismissal",d:"If no query or hearing preceded dismissal, document the sequence and seek advice on unfair-dismissal remedies."}],
  faqs:[{q:"Can my boss sack me without reason?",a:"It depends on your contract type and applicable law — some regimes require reason and process. Get advice with your documents."},{q:"What is the minimum wage?",a:"A statutory minimum exists and is amended over time — verify the current figure from official sources before quoting it."}],
  related:["association","women","disability","digital"], orgs:["Legal Aid (free legal assistance)"], sources:["VERIFY: Labour Act; Minimum Wage Act (current amendment); NICN rules."],
  keywords:"employment work job sack dismiss salary wage pension leave maternity harassment" },
{ id:"tenancy", icon:"🏠", title:"Rent & Tenancy Rights", status:"overview",
  summary:"Rent agreements, notice periods, lawful eviction, and what to do about lockouts or illegal demolition.",
  explanation:["Tenancy rules differ by state — notice periods and court processes depend on your state's law and your tenancy type.","Self-help (changing locks, removing roofs, cutting utilities) is the classic unlawful eviction pattern."],
  legalBasis:{ text:"General information: state tenancy/rent laws (verify your state's current law and notice periods).", status:"verify" },
  meaning:["A landlord must end tenancy through proper notice and court process, not force.","You owe agreed rent; the landlord owes habitable premises and agreed services.","Receipts and written agreements decide most disputes."],
  canDo:["Insist on written agreements and receipts for every payment (transfer narrations help).","If locked out, photograph it, keep messages, and report promptly — do not break back in violently.","Respond to court processes; never ignore a summons."],
  avoid:["Do not stop paying rent without advice merely because of disrepair — follow formal complaint steps.","Do not withhold keys or property to enforce your own claims.","Do not sign 'voluntary quit' papers under pressure without advice."],
  examples:[{t:"Changed locks",d:"A lockout while your tenancy subsists is the textbook case for urgent complaint with photos and receipts."},{t:"Rent increase",d:"Increases generally apply per agreement/notice rules — get the demand in writing and check your agreement."}],
  faqs:[{q:"How much notice must my landlord give?",a:"It depends on tenancy type and state law — check your agreement and your state's rules (verify). "},{q:"Can I be evicted without going to court?",a:"Lawful eviction runs through court process; forcible self-help eviction is challengeable."}],
  related:["property","dignity","consumer"], orgs:["Legal Aid (free legal assistance)"], sources:["VERIFY: your state's tenancy law; court procedure rules."],
  keywords:"rent tenancy landlord evict notice quit lockout house shop agreement receipt" },
{ id:"consumer", icon:"🛒", title:"Consumer Rights", status:"overview",
  summary:"Faulty goods, failed services, fake products, refunds and how to complain effectively.",
  explanation:["Buyers are protected against defective goods, failed services, and unsafe products — but outcomes depend on evidence and following complaint steps.","Sector regulators (telecoms, banking, food/drugs, aviation) each run their own complaint channels (verify current portals)."],
  legalBasis:{ text:"General information: Federal Competition and Consumer Protection Act 2018 (verify); sector regulator rules.", status:"verify" },
  meaning:["Goods should match their description and be of acceptable quality.","Services paid for should be delivered as agreed, or refunded/compensated per terms and law.","Unsafe or fake regulated products (drugs, foods) should also be reported for public safety."],
  canDo:["Keep receipts, warranties, packaging, screenshots and photos.","Complain in writing to the seller first: state the fault, your remedy, and a deadline.","Escalate to the relevant regulator or consumer body with your paper trail."],
  avoid:["Do not throw away packaging/receipts until a complaint is resolved.","Do not accept 'no refund' signs as the final word where the law implies remedies.","Do not consume or use a product you suspect is fake or unsafe."],
  examples:[{t:"Dead-on-arrival phone",d:"A dated written complaint with receipt and unboxing photos usually resolves faster than charger-stall arguments."},{t:"Failed transfer, debited",d:"Keep the reference number, alert your bank in writing, and escalate through the official dispute channel."}],
  faqs:[{q:"The seller says 'no return, no refund' — is that final?",a:"Not necessarily; statutory rights can override shop policies — escalate with evidence."},{q:"Where do I report fake drugs?",a:"Through the appropriate health-safety channel — verify the current reporting route in official guidance."}],
  related:["digital","property","tenancy"], orgs:["Legal Aid (free legal assistance)"], sources:["VERIFY: FCCPA 2018; regulator complaint procedures."],
  keywords:"consumer refund goods faulty fake warranty seller market" },
{ id:"women", icon:"♀", title:"Women's Rights", status:"overview",
  summary:"Protection against discrimination and gender-based violence, plus marriage, inheritance and workplace rights.",
  explanation:["Women hold the same fundamental rights as men, with additional specific protections against gender-based violence and discrimination.","Safety comes first: medical care, safe shelter, and trusted support before paperwork."],
  legalBasis:{ text:"General information: VAPP Act 2015 (federal; domesticated unevenly by states — verify your state's position) and state family/gender laws.", status:"verify" },
  meaning:["No one may beat, threaten, coerce or sexually assault you — consent and safety are the lines.","Workplace discrimination, denial of inheritance, and forced marriage are challengeable.","Survivors are entitled to care, not blame."],
  canDo:["If unsafe, get to safety and seek medical care promptly; keep the medical report.","Document incidents (dates, messages, photos, witnesses) and store copies with someone trusted.","Contact support services and consider legal advice before confronting the perpetrator."],
  avoid:["Do not wash away evidence before medical examination after assault.","Do not sign family 'settlement' papers under pressure without independent advice.","Do not stay silent because of stigma — confidential support exists."],
  examples:[{t:"Workplace harassment",d:"A dated log of incidents plus saved messages turns 'my word vs theirs' into a documented pattern."},{t:"Inheritance denial",d:"Being excluded from family property on gender grounds can be challenged — gather documents and get advice."}],
  faqs:[{q:"Does the VAPP Act apply in my state?",a:"It is federal law with uneven state domestication — verify your state's position with a lawyer or support service."},{q:"Where can I get confidential help?",a:"Support services exist through government and civil-society groups — verify current helplines via official directories."}],
  related:["children","dignity","employment","fundamental"], orgs:["Domestic & sexual-violence support services","Legal Aid (free legal assistance)","Human-rights protection body"], sources:["VERIFY: VAPP Act 2015; your state's family/gender laws."],
  keywords:"women gender domestic violence assault marriage inheritance discrimination" },
{ id:"children", icon:"🧒", title:"Children's Rights", status:"overview",
  summary:"Every child's right to safety, education, health and protection from abuse, neglect and exploitation.",
  explanation:["Children enjoy special protection because of their vulnerability — covering survival, development, protection and participation.","Adults who suspect abuse should act: the child's immediate safety outweighs every other consideration."],
  legalBasis:{ text:"General information: Child Rights Act 2003 (federal; domesticated unevenly by states — verify) plus state laws.", status:"verify" },
  meaning:["Children have rights to free basic education, health care and protection from abuse and exploitation.","Child labour, trafficking and sexual abuse are grave offences.","Schools and caregivers owe children a duty of care."],
  canDo:["Report suspected abuse to appropriate authorities promptly; preserve any evidence.","Get the child medical care and psychosocial support without delay.","Choose schools carefully and monitor wellbeing; raise concerns in writing."],
  avoid:["Do not confront suspected abusers in ways that endanger the child.","Do not share a child's abuse story publicly with identifying details.","Do not delay medical examination after suspected sexual abuse."],
  examples:[{t:"Teacher hitting a pupil",d:"Corporal excess causing injury should be reported to school authorities and beyond — photograph injuries and get care."},{t:"Street hawking instead of school",d:"Persistent denial of schooling and exploitative labour can be reported to child-protection channels."}],
  faqs:[{q:"Does the Child Rights Act apply in my state?",a:"Domestication is uneven — verify your state's position."},{q:"Who can report on a child's behalf?",a:"Any concerned adult — parents, relatives, teachers, neighbours — should prioritise the child's safety and report."}],
  related:["women","education","dignity","fundamental"], orgs:["Child-protection services","Legal Aid (free legal assistance)","Domestic & sexual-violence support services"], sources:["VERIFY: Child Rights Act 2003; your state's child-protection laws."],
  keywords:"children child school abuse education trafficking minor custody" },
{ id:"disability", icon:"♿", title:"Disability Rights", status:"overview",
  summary:"Equal access to public services, education, work and buildings — and protection against discrimination.",
  explanation:["Persons with disabilities are entitled to dignity, inclusion, and reasonable accommodation — not charity.","Barriers may be physical (steps, no ramps), communicational (no sign interpretation), or attitudinal."],
  legalBasis:{ text:"General information: Discrimination Against Persons with Disabilities (Prohibition) Act 2018 (verify provisions) plus state rules.", status:"verify" },
  meaning:["Discrimination in public services and employment on disability grounds is challengeable.","Public buildings and services should be accessible.","Students and workers are entitled to reasonable accommodation."],
  canDo:["Document barriers (photos, dates, correspondence) and request accommodation in writing.","Apply for advertised disability quotas and support schemes through official channels (verify current schemes).","Connect with disability organisations for guidance on complaints."],
  avoid:["Do not accept verbal refusals — ask for written reasons.","Do not let 'no provision' stop you; the law anticipates progressive compliance.","Do not disclose more medical detail than necessary in complaints."],
  examples:[{t:"Inaccessible bank branch",d:"A written request for a ramp or alternative service creates the paper trail a complaint needs."},{t:"Exam without accommodation",d:"Request extra time or assistive arrangements ahead of the exam, in writing, with medical backing."}],
  faqs:[{q:"What counts as reasonable accommodation?",a:"Adjustments that remove barriers without imposing disproportionate burden — assessed case by case."},{q:"Can I be denied a job because of disability?",a:"Blanket exclusion on disability grounds is challengeable — document the process and seek advice."}],
  related:["employment","education","dignity","fundamental"], orgs:["Disability support organisations","Legal Aid (free legal assistance)"], sources:["VERIFY: Disabilities (Prohibition) Act 2018; state rules."],
  keywords:"disability accessible discrimination wheelchair accommodation inclusion" },
{ id:"education", icon:"🎓", title:"Education Rights", status:"overview",
  summary:"Admission fairness, fees disputes, exams, NYSC mobilisation and handling campus harassment.",
  explanation:["Basic education is free and compulsory in policy; tertiary and professional training run on institutional rules plus official regulator guidelines.","Most education disputes are won on paper: admission letters, receipts, results, and dated correspondence."],
  legalBasis:{ text:"General information: UBE Act 2004 (verify); institutional regulations; exam-body and NYSC official guidelines (verify current versions).", status:"verify" },
  meaning:["No child should be denied basic education on improper grounds.","Fees charged must follow the institution's approved schedule — arbitrary levies are queryable.","Students are protected against harassment and extortion by staff."],
  canDo:["Keep every admission letter, fee receipt, result slip and official message.","Raise disputes in writing through the institution's formal channels first.","Report harassment or 'sorting' demands with evidence to the institution and appropriate authorities."],
  avoid:["Do not pay undocumented levies into private accounts — demand official receipts.","Do not forge results or certificates — the criminal consequences are severe.","Do not ignore matriculation, clearance and mobilisation deadlines."],
  examples:[{t:"Withheld result over fees",d:"If fees are actually paid, receipts plus a written request usually unlock the result."},{t:"Lecturer demanding money",d:"A documented demand (messages, witnesses) reported formally protects you and others."}],
  faqs:[{q:"Can a school send my child home over fees?",a:"Schools have fee policies, but abrupt exclusion mid-term over disputed fees can be queried — engage the proprietor/ministry formally."},{q:"My NYSC mobilisation has issues — what now?",a:"Follow the official NYSC procedure for your case type via official portals only (verify URLs); beware fraudsters."}],
  related:["children","women","disability","digital"], orgs:["Child-protection services","Legal Aid (free legal assistance)"], sources:["VERIFY: UBE Act 2004; institutional handbooks; exam-body/NYSC official guidelines."],
  keywords:"education school student university jamb waec neco nysc fees admission result" },
{ id:"digital", icon:"📱", title:"Digital & Online Rights", status:"overview",
  summary:"Privacy, data protection, online scams, cyberbullying and what to do when your accounts or money are attacked.",
  explanation:["Online life carries real-world liability: posts can defame, transfers can be fraud, and apps can misuse your data.","The first hour after a scam determines recovery chances — act fast, in the right order."],
  legalBasis:{ text:"General information: cybercrime legislation (as amended — verify) and the Nigeria Data Protection Act 2023 (verify).", status:"verify" },
  meaning:["Your personal data must be handled lawfully and securely by those who hold it.","Fraud, hacking, impersonation and non-consensual intimate-image sharing are serious matters.","Platforms and banks have dispute and reporting mechanisms you should use immediately."],
  canDo:["Never share OTPs, passwords or bank details — legitimate agents never ask.","Screenshot everything at once: chats, profiles, alerts, reference numbers.","Alert your bank/platform first, then the appropriate law-enforcement channel, with your reference numbers."],
  avoid:["Do not 'chase' scammers with more payments to recover losses.","Do not click links in suspicious SMS/emails purporting to be your bank.","Do not share nude images or allow secret recordings — and report coercion immediately."],
  examples:[{t:"Fake vendor",d:"Paid for goods that never arrived? Screenshots plus bank reference plus a written platform report is the recovery path."},{t:"SIM-swap alert",d:"Unexpected 'SIM update' messages warrant an immediate call to your network and bank on verified numbers."}],
  faqs:[{q:"Can the bank reverse my transfer to a scammer?",a:"Sometimes, if alerted very quickly with the reference — speed is everything; outcomes are not guaranteed."},{q:"Someone posted my pictures without consent — what do I do?",a:"Screenshot, report to the platform, preserve evidence, and seek advice — especially for intimate images."}],
  related:["privacy","consumer","expression","education"], orgs:["Human-rights protection body"], sources:["VERIFY: Cybercrimes Act (current amendment); NDPA 2023 and regulator guidance."],
  keywords:"digital online scam fraud otp data privacy cyberbullying social media bank transfer" },
{ id:"constitutional", icon:"📜", title:"Constitutional Rights & Structure", status:"overview",
  summary:"How Nigeria is governed — the arms of government, how laws are made, and how citizens can engage the system.",
  explanation:["The Constitution is supreme: any law inconsistent with it is void to the extent of the inconsistency.","Power is shared between the federal and state governments, and separated among the executive, legislature and judiciary."],
  legalBasis:{ text:"General information: 1999 Constitution of Nigeria (as amended — verify official text); National Assembly procedures (verify).", status:"verify" },
  meaning:["Laws are made by the National Assembly (federal) and Houses of Assembly (states).","Courts interpret laws and settle disputes, up to the Supreme Court.","Citizens engage through voting, petitions, public hearings and constituency offices."],
  canDo:["Follow bills that affect you and attend/submit to public hearings when invited.","Know your representatives and engage their constituency offices in writing.","Use lawful information requests and petitions to demand accountability."],
  avoid:["Do not rely on social-media summaries of the Constitution for serious matters — read the official text.","Do not confuse executive orders and press statements with enacted law.","Do not ignore jurisdiction: start cases in the right court with advice."],
  examples:[{t:"New levy announced",d:"Ask: which law authorises it, passed by which house, signed when? Legitimate levies trace to legislation."},{t:"Court hierarchy",d:"A magistrate-court matter and a fundamental-rights suit belong in different courts — jurisdiction matters."}],
  faqs:[{q:"Is the Constitution above every other law?",a:"Yes — it is the supreme law; inconsistent laws are void to the extent of inconsistency."},{q:"How can I participate in lawmaking?",a:"Through voting, memoranda to committees, public hearings, petitions and constituency engagement."}],
  related:["fundamental","civic","fair-hearing","property"], orgs:["Human-rights protection body"], sources:["VERIFY: official text of the 1999 Constitution (as amended)."],
  keywords:"constitution government senate house reps governor president judiciary court assembly law" },
{ id:"civic", icon:"🗳", title:"Civic Responsibilities", status:"overview",
  summary:"Voting, taxes, obeying the law, community service and holding leaders accountable — the citizen's side of the bargain.",
  explanation:["Rights work best where citizens also honour duties: obeying lawful orders, paying lawful taxes, and participating in democracy.","An engaged citizenry — voting, watching, asking — is the strongest rights-protection system."],
  legalBasis:{ text:"General information: Electoral Act 2022 (verify), INEC voter guidelines (verify current), applicable tax laws (verify).", status:"verify" },
  meaning:["Register, collect your PVC, and vote — your vote is your formal voice.","Pay taxes and levies backed by law; demand receipts.","Protect public property and report crime and malpractice."],
  canDo:["Register to vote and verify your polling unit before election day.","Observe elections lawfully or report malpractice through official channels.","Attend town halls and engage representatives with written, specific asks."],
  avoid:["Do not sell your vote — it trades away your leverage and is unlawful.","Do not spread unverified election results or incite unrest.","Do not evade lawful taxes; challenge unlawful levies through proper channels instead."],
  examples:[{t:"Vote-buying offer",d:"Collecting money for your vote is unlawful and weakens your community's bargaining power — decline and report."},{t:"Community project",d:"Residents who track a constituency project's budget and progress get better completion rates."}],
  faqs:[{q:"My PVC is lost — can I still vote?",a:"Follow INEC's current procedure for lost/damaged cards — verify the latest official guideline."},{q:"How do I report vote-buying?",a:"Document safely (photos, location, time) and report through official election-security channels."}],
  related:["constitutional","expression","association","education"], orgs:["Human-rights protection body"], sources:["VERIFY: Electoral Act 2022; INEC guidelines; tax statutes."],
  keywords:"civic vote pvc inec election tax responsibility duty community ballot" },
{ id:"environment", icon:"🌳", title:"Environmental Rights", status:"overview",
  summary:"The right to a clean, healthy environment — pollution complaints, community advocacy, and official reporting channels.",
  explanation:["Oil spills, gas flaring, illegal dumping, and uncontrolled emissions affect health, livelihoods and property.","Communities can document harm, demand remediation, and escalate through environmental regulators and the courts (with advice)."],
  legalBasis:{ text:"General information: environmental statutes and regulations apply at federal and state levels — verify the current regulator and procedure for your case.", status:"verify" },
  meaning:["You are entitled to an environment adequate for health and wellbeing.","Polluters can be required to stop, clean up and compensate through proper process.","Communities should be consulted on projects affecting them (verify EIA requirements)."],
  canDo:["Document pollution: dated photos/videos, health complaints, dead crops or fish, witness statements.","Report to the relevant environmental regulator in writing and keep copies.","Organise peaceful community advocacy; seek legal advice before litigation."],
  avoid:["Do not vandalise company or government property in protest — it undermines your case.","Do not drink or use water you suspect is contaminated.","Do not sign compensation documents without independent advice."],
  examples:[{t:"Factory smoke",d:"A dated log of emissions plus clinic records of respiratory complaints builds a reportable pattern."},{t:"Oil spill",d:"Photograph spread, affected farms/water, and response (or lack of it) before cleanup alters the scene."}],
  faqs:[{q:"Which agency handles pollution complaints?",a:"It depends on the pollutant and location (federal/state regulators) — verify the current channel for your case."},{q:"Can communities get compensation?",a:"Remediation and compensation claims are possible through proper process — document harm and get advice early."}],
  related:["life","property","fundamental","civic"], orgs:["Human-rights protection body"], sources:["VERIFY: applicable environmental statutes/regulations; EIA requirements."],
  keywords:"environment pollution spill flaring dumping clean water air oil" },
{ id:"marriage", icon:"💍", title:"Marriage & Family Rights", status:"overview",
  summary:"Consent, registration, bride price and family duties — the rights of spouses and children before and after the ceremony.",
  explanation:["Marriages in Nigeria are celebrated under different systems — civil (statutory), customary and Islamic — and the rules that apply depend on which one you used.","Family disputes over maintenance, custody, property and in-law interference are far easier to handle when you have the certificate, receipts and messages."],
  legalBasis:{ text:"General information: the Marriage Act governs civil marriage; customary and Islamic law govern other marriages, with state rules differing — verify the rules that apply to your marriage type.", status:"verify" },
  meaning:["Both spouses must freely consent — a ceremony forced by pressure, threats or deception is not valid consent.","Keep the marriage certificate, dowry/bride-price records and proof of contributions to the household.","Spouses and children are entitled to maintenance and protection from violence — see also Women's and Children's Rights."],
  canDo:["Register the marriage properly and keep the original certificate somewhere safe.","Agree bride price/dowry terms openly and keep receipts; involve families in writing where disputes start.","If you feel pressured or unsafe, seek advice early — family-law problems move faster with documents."],
  avoid:["Do not enter a second marriage without understanding the legal consequences for the first (verify the position for your marriage type).","Do not destroy certificates or messages during a dispute — they are evidence.","Do not draw children into adult family conflicts."],
  examples:[{t:"Lost certificate",d:"A lost marriage certificate can usually be re-issued — start with the registry that issued it."},{t:"In-law seizure",d:"Family members taking your property or threatening you should be documented and reported — being related does not suspend the law."}],
  faqs:[{q:"Is a traditional wedding a valid marriage?",a:"It can be valid under customary law, with different legal effects from a civil ceremony — get advice for your situation."},{q:"Can my husband's family chase me out?",a:"It depends on your marriage type, your contributions and the facts — document everything and get advice quickly."}],
  related:["divorce","women","children","property","fundamental"], orgs:["Legal Aid (free legal assistance)","Domestic & sexual-violence support services"], sources:["VERIFY: Marriage Act (as amended); state marriage/registration rules; Child Rights Act 2003 minimum marriage age (state domestication varies)."],
  keywords:"marriage marry family wife husband wedding ceremony registration certificate bride price dowry in-law maintenance spouse" },
{ id:"divorce", icon:"🧾", title:"Divorce & Separation", status:"overview",
  summary:"How separation and dissolution actually work: grounds, custody, maintenance, property and the court path.",
  explanation:["Divorce (dissolution) is a court process — leaving the house, separating, or announcing it on social media does not by itself end a marriage.","Courts consider the breakdown of the marriage, and settle custody, maintenance and property alongside or shortly after the decree (procedures vary by marriage type)."],
  legalBasis:{ text:"General information: matrimonial-cases legislation applies to statutory marriages; customary and Islamic processes differ; the High Court of your state has jurisdiction — verify the procedure for your marriage type.", status:"verify" },
  meaning:["Separation and divorce are different legal states — separation does not end the marriage.","The welfare of children is the priority in custody and access decisions.","Maintenance and property claims are stronger where contributions and income can be evidenced."],
  canDo:["Leave safely first if you are at risk, then take advice on the formal steps.","Gather documents: certificate, children's school and health records, bank statements, property papers.","Respond to every court process — ignoring a summons damages your case."],
  avoid:["Do not withhold contact with the children as leverage — it can count against you in custody.","Do not sign away property or maintenance rights under pressure without independent advice.","Do not contract a new marriage before the earlier one is lawfully dissolved."],
  examples:[{t:"Moved out in anger",d:"Moving out begins separation, not divorce — get advice immediately on status, children and finances."},{t:"House in one name",d:"Contributions you can evidence (receipts, transfers, building materials) matter in property claims — start collecting them now."}],
  faqs:[{q:"How long does a divorce take?",a:"It depends on the court, the case and whether terms are agreed — ask a lawyer for a realistic timeline in your state."},{q:"Who gets the children?",a:"The child's welfare is central; care, schooling and access are decided on the facts — seek advice early."}],
  related:["marriage","women","children","property","fundamental"], orgs:["Legal Aid (free legal assistance)","Child-protection services"], sources:["VERIFY: applicable matrimonial-cases legislation; your state High Court family procedure; customary/Islamic law alternatives."],
  keywords:"divorce separation dissolution marriage ends custody maintenance alimony property decree court split leaving husband wife" },
{ id:"health", icon:"🏥", title:"Health & Medical Rights", status:"overview",
  summary:"Consent to treatment, your records and bills, confidentiality, and what to do about negligence or refused care.",
  explanation:["Patients are entitled to be told what is wrong, what is proposed, the risks and the cost — and to accept or refuse it.","Medical records and itemised bills should be obtainable, and complaints about care should be documented while the facts are fresh."],
  legalBasis:{ text:"General information: health-sector regulations, professional codes and consumer-protection rules apply — verify the current complaint channel for your case.", status:"verify" },
  meaning:["You may refuse a treatment you do not understand or do not want, except where lawful emergency rules apply (verify).","Your health information should be kept confidential by providers.","Facilities able to treat you may be limited in refusing emergency care — verify current emergency-treatment rules."],
  canDo:["Ask for a written diagnosis, proposed procedure and itemised bill; keep every receipt and report.","Request a copy of your medical records from the hospital or clinic.","If something went wrong, preserve the file, receipts and staff names, then complain to the facility and the regulator."],
  avoid:["Do not stop prescribed treatment without speaking to a qualified professional first.","Do not sign consent forms you have not had explained — ask questions until you understand.","Do not delay a complaint — records and memories fade quickly."],
  examples:[{t:"Unexplained charges",d:"An itemised bill checked against receipts often resolves hospital over-charges without litigation."},{t:"Refused admission",d:"Note the time, facility, reason and names — emergency-refusal complaints are decided on that record."}],
  faqs:[{q:"Can I see my medical records?",a:"You can request them from your provider; charges and procedures vary — put the request in writing."},{q:"A hospital demands cash before treatment — is that allowed?",a:"Facilities have payment policies, but emergency-treatment rules may limit outright refusal — document the situation and seek advice."}],
  related:["consumer","children","women","disability","fundamental"], orgs:["Legal Aid (free legal assistance)","Disability support organisations"], sources:["VERIFY: current health-sector regulations and professional codes; national health-insurance arrangements (verify eligibility); regulator complaint channels."],
  keywords:"health medical hospital treatment nurse doctor bill records consent negligence emergency care patient prescription" },
{ id:"food-safety", icon:"🍽", title:"Food & Food-Safety Rights", status:"overview",
  summary:"Expired, fake or contaminated food and medicine — how to spot it, report it and protect your family.",
  explanation:["Food and medicines sold to you must be fit to consume; expired, contaminated or counterfeited products are a public-health matter, not just a seller's problem.","Reporting a bad product protects other buyers too — keep the packaging, batch details, expiry date and where you bought it."],
  legalBasis:{ text:"General information: food and drug safety regulators (including NAFDAC) and consumer-protection law apply — verify the current reporting channel before filing.", status:"verify" },
  meaning:["You are entitled to expect that food and medicines sold to you are safe and properly labelled.","Selling expired or unlabelled food and drugs can be reported.","Suspect products should be preserved (pack, batch, expiry, photos) before disposal."],
  canDo:["Check expiry dates, seals and packaging before buying anything consumable.","Report unsafe products with pack, batch number, purchase location and date.","Seek medical care promptly if you or a child falls ill after suspect food; keep the clinic report."],
  avoid:["Do not consume food or medicine you suspect is expired or spoiled.","Do not buy medicines from unverified street or unknown online sellers.","Do not throw away packaging before reporting — it is your evidence."],
  examples:[{t:"Expired drink",d:"Photograph the pack and expiry date, keep it, and report to the seller and the regulator with the batch details."},{t:"Illness after street food",d:"A clinic record plus where and when you bought it makes a reportable pattern — report to the local health/environmental authority (verify your state's channel)."}],
  faqs:[{q:"Where do I report fake food or drugs?",a:"Through the appropriate national food-and-drug safety channel — verify the current portal or hotline in official guidance."},{q:"A seller refuses to take back expired goods?",a:"Escalate with receipt and photos through the consumer-protection channel (verify the current route)."}],
  related:["consumer","children","health","fundamental"], orgs:["Legal Aid (free legal assistance)","Child-protection services"], sources:["VERIFY: food and drug safety regulations; NAFDAC reporting route; consumer-protection complaint procedure."],
  keywords:"food safety expiry expired spoiled rotten fake drugs nafdac contaminated water street food poisoning batch label drink" },
{ id:"banking", icon:"🏦", title:"Financial & Banking Rights", status:"overview",
  summary:"Failed transfers, unauthorised debits, hidden charges, loan-app harassment — and how to escalate a bank complaint.",
  explanation:["Banks and payment providers owe you accurate records, advance disclosure of charges, and a working dispute process for failed or unauthorised transactions.","Speed matters: report failed transfers and card fraud the same day and keep the reference number."],
  legalBasis:{ text:"General information: central-bank consumer-protection requirements and deposit-insurance arrangements apply — verify current rules, limits and complaint routes.", status:"verify" },
  meaning:["You can demand an explanation for any debit you did not authorise.","Charges should be disclosed in advance — undisclosed fees are queryable.","Eligible deposits are insured up to a current limit — verify that limit with the deposit-insurance body."],
  canDo:["Keep alerts, reference numbers, statements and the recipient's details for every dispute.","Complain to your bank in writing first with dates and references; escalate if unresolved.","Use official channels only: your bank's published lines and the central bank's consumer complaint route (verify the current portal)."],
  avoid:["Do not share OTP, PIN or card details with anyone — including people claiming to be bank staff.","Do not let strangers 'help you transfer' using your card or phone.","Do not miss dispute deadlines — most schemes are time-sensitive."],
  examples:[{t:"Debited, not delivered",d:"A written dispute with reference number and statement, filed within days, normally triggers reversal checks."},{t:"Loan-app harassment",d:"Screenshots sent to your bank plus the data-protection complaint channel are the documented path (see Digital Rights)."}],
  faqs:[{q:"My transfer failed but money left my account — what now?",a:"Report immediately with the reference number; timelines depend on the bank and the scheme — escalate in writing if delayed."},{q:"Is my money safe if my bank fails?",a:"Eligible deposits are insured up to a current limit — verify the limit with the deposit-insurance body."}],
  related:["consumer","digital","employment","property"], orgs:["Legal Aid (free legal assistance)"], sources:["VERIFY: central-bank consumer-protection requirements; deposit-insurance coverage limits; your bank's published complaint procedure."],
  keywords:"bank banking transfer failed debit charge otp pos loan app interest deposit insurance ndic cbn dispute reversal atm" },
{ id:"international", icon:"🌍", title:"International Human Rights", status:"overview",
  summary:"Where Nigerian rights connect to African and global standards — treaties, petitions and regional courts.",
  explanation:["Nigeria's Constitution sits alongside international and regional commitments, including the African Charter on Human and Peoples' Rights.","Regional bodies — the African Commission and the ECOWAS Community Court — can hear human-rights matters involving states, subject to their own rules (verify standing, deadlines and procedure)."],
  legalBasis:{ text:"General information: African Charter on Human and Peoples' Rights (ratified by Nigeria), ECOWAS treaty framework and UN human-rights instruments — verify current procedure and any domestication before relying on a provision.", status:"verify" },
  meaning:["Regional standards influence how Nigerian courts read fundamental-rights provisions.","Regional petitions usually require you to first exhaust remedies in Nigeria (verify the rule for each body).","These routes address state conduct — they are not a substitute for a lawyer in an ordinary private dispute."],
  canDo:["Read the official texts of any instrument before quoting it.","Exhaust domestic remedies first and keep proof of every step.","Seek advice from a human-rights organisation before filing outside Nigeria (verify current contacts)."],
  avoid:["Do not assume a treaty quoted online applies directly in Nigeria — check domestication.","Do not miss regional deadlines — procedure and time limits are strict.","Do not use a regional complaint to replace urgent local steps such as bail, safety or medical care."],
  examples:[{t:"Exhaustion rule",d:"A regional petition can fail because domestic remedies were skipped — take advice before filing."},{t:"Citing the Charter",d:"Legal arguments often rest on the African Charter — quote the official text, not a blog summary."}],
  faqs:[{q:"Can I take Nigeria to an international court?",a:"Routes exist through regional and UN bodies, subject to their rules and remedies requirements — get specialist advice first."},{q:"Does the African Charter apply in Nigeria?",a:"Nigeria is a party to it; how it is used in domestic courts depends on the case — verify with a practitioner."}],
  related:["fundamental","civic","constitutional","dignity"], orgs:["Human-rights protection body","Legal Aid (free legal assistance)"], sources:["VERIFY: African Charter on Human and Peoples' Rights; ECOWAS Community Court rules; UN instruments and Nigeria's ratifications."],
  keywords:"international african charter ecowas court commission un treaty petition regional human rights banjul" }
];

/* Derived category cards — ONE source of truth for every category grid on the site.
   Primary (headline) categories are listed first so homepage/library ordering stays stable;
   every other entry above follows in file order. Presentation order only — no content here. */
window.RA_RIGHTS_PRIMARY = ["fundamental","police","employment","tenancy","consumer","women",
  "children","disability","education","digital","constitutional","civic"];
window.RA_RIGHTS = (function(){
  var D = window.RA_RIGHTS_DETAIL || [];
  var primary = window.RA_RIGHTS_PRIMARY;
  var card = function(r){
    var c = { id:r.id, icon:r.icon, title:r.title, summary:r.summary, status:r.status,
      keywords:r.keywords||"", fullGuide:r.fullGuide };
    if(r.legalBasis && r.legalBasis.text) c.source = r.legalBasis.text;
    if(r.meaning && r.meaning.length) c.points = r.meaning.slice(0,4);
    return c;
  };
  var head = [], tail = [], seen = {};
  D.forEach(function(r){
    var i = primary.indexOf(r.id);
    if(i > -1 && !seen[r.id]){ seen[r.id] = 1; head[i] = card(r); }
    else { seen[r.id] = 1; tail.push(card(r)); }
  });
  return head.filter(function(x){ return !!x; }).concat(tail);
})();
